INSERT INTO `company` (`name`, `country`) VALUES ('Apple', 'USA');
INSERT INTO `company` (`name`, `country`) VALUES ('Samsung', 'South Korea');
INSERT INTO `company` (`name`, `country`) VALUES ('Xiaomi', 'China');
INSERT INTO `company` (`name`, `country`) VALUES ('Huawei', 'China');
INSERT INTO `company` (`name`, `country`) VALUES ('Meizu', 'China');
INSERT INTO `company` (`name`, `country`) VALUES ('Sony', 'Japan');
INSERT INTO `company` (`name`, `country`) VALUES ('LG', 'South Korea');
INSERT INTO `company` (`name`, `country`) VALUES ('Lenovo', 'China');
INSERT INTO `company` (`name`, `country`) VALUES ('Motorola', 'China');
INSERT INTO `company` (`name`, `country`) VALUES ('Google', 'USA');
